apiVersion: v1
kind: Service
metadata:
  name: cns-wesbite
  labels:
    run: cns-wesbite
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: cns-wesbite